openapi: 3.0.3
info:
  title: Call Forwarding Signal Age Verification Roaming status retrieval API
  description: '# Overview

    The Call Forwarding Signal API provides the API Consumer with

    information about the status of the Call Forwarding Service on a specific

    phone number. The main scope of the Call Forwarding Signal API is "anti

    Fraud" to avoid fraudsters to use the Call Forwarding Service to carry

    on a scam. Other use cases are anyway supported by the Call Forwarding

    Signal API that also

    provides additional endpoints to detect the general Call Forwarding

    Service settings.

    # Introduction

    The Call Forwarding Service is provided by the Network to a phone

    number. This service redirects the incoming call to that phone number

    to an alternative destination such as another phone number or a voice mail

    system. There are two main types of call forwarding settings:

    unconditional and conditional.

    The Call Forwarding Signal API can be invoked to detect if the unconditional

    call forwarding service is active. The Call Forwarding Signal API can also

    be invoked to

    get the general status of the Call Forwarding Service (inactive,

    conditional, unconditional). If conditional call forwarding is active,

    the different type of settings are returned (''conditional_busy'',

    ''conditional_not_reachable'', ''conditional_no_answer'').


    **Example use cases:**


    [**Bank Frauds**](https://github.com/camaraproject/CallForwardingSignal/discussions/3#discussioncomment-8694420)


    [**Alert Interception**](https://github.com/camaraproject/CallForwardingSignal/discussions/3#discussioncomment-8701847)


    [**Call Forwarding Verification**](https://github.com/camaraproject/CallForwarding\Signal/discussions/3#discussioncomment-8915595)

    # Quick Start

    The Call Forwarding Signal API is a REST API based on the

    CreateCallForwardingSignal resource.

    This resource can be used, by the API Consumer, to specify the phone number

    on which the Call Forwarding Service status must be verified, in case of

    two-legged authentication. If three-legged authentication is used the phone

    number is instead detected, by the API Producer, from the access token.


    Before starting to use the Call Forwarding API, the developer needs to know

    about the below specified details:


    **phoneNumber**

    This is the end user phone number. The Call Forwarding Signal API verifies

    if a call forwarding

    service is active on this phone number. Note: this parameter must be

    must be provided/valued only in case of two-legged authentication.

    In case of three-legged authentication the phone number is retrieved by

    the access token.


    **CreateCallForwardingSignal**

    This is the resource the API Consumer uses to define the phone number to

    be verified about the status of the Network Call Forwarding service.


    **UnconditionalCallForwardingSignal**

    This is the resource the API Consumer gets back, containing the information

    about the Unconditional Call Forwarding Service status for the given phone

    number (PhoneNumber).


    **CallForwardingSignal**

    This is the resource the API Consumer gets back, containing the information

    about the general status of the Network Call Forwarding service for the

    specified phone number.


    The Call Forwarding Signal API provides two endpoints fulfilling the

    following intents:

    - **unconditional-call-forwardings**: Is the unconditional call fwd service

    active on a specific phone number?

    - **call-forwardings**: Which is the status of the call forwarding for a

    specific phone number?

    # API Documentation

    ## Details

    The Call Forwarding Signal API is invoked by an API Consumer after the

    Consent Management flow.


    The API Consumer can request the API Producer for the status of the

    Unconditional Call Forwarding service using the

    unconditional-call-forwardings POST method. A boolean, with the information

    about the activation status of the call forwarding service, will be

    provided back via the UnconditionalCallForwardingSignal resource.


    The API Consumer can also request the API Producer for the generic status of

    the Call Forwarding service using the call-forwardings POST method. An array

    of strings with the information of the type of active call forwarding

    services will be provided back via the CallForwardingSignal resource.

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how

    an API consumer requests an access token. Please refer to Identity and

    Consent Management

    (https://github.com/camaraproject/IdentityAndConsentManagement/)

    for the released version of the profile.


    The specific authorization flows to be used will be agreed upon during the

    onboarding process, happening between the API consumer and the API

    provider, taking into account the declared purpose for accessing the API,

    whilst also being subject to the prevailing legal framework dictated by

    local legislation.


    In cases where personal data is processed by the API and users can

    exercise their rights through mechanisms such as opt-in and/or opt-out,

    the use of three-legged access tokens is mandatory. This ensures that

    the API remains in compliance with privacy regulations, upholding the

    principles of transparency and user-centric privacy-by-design.

    # Identifying the phone number from the access token

    This API requires the API consumer to identify a phone number as the

    subject of the API as follows:

    - When the API is invoked using a two-legged access token, the subject

    will be identified from the optional `phoneNumber` object field, which

    therefore MUST be provided.

    - When a three-legged access token is used however, this optional

    identifier MUST NOT be provided, as the subject will be uniquely

    identified from the access token.


    This approach simplifies API usage for API consumers using a

    three-legged access token to invoke the API by relying on the

    information that is associated with the access token and was

    identified during the authentication process.

    ## Error handling:


    - If the subject cannot be identified from the access token and the

    optional `phoneNumber` object field is not included in the request, then

    the server will return an error with the

    `422 MISSING_IDENTIFIER` error code.


    - If the subject can be identified from the access token and the

    optional `phoneNumber` object field is also included in the request, then

    the server will return an error with the `422 UNNECESSARY_IDENTIFIER`

    error code. This will be the case even if the same device is

    identified by these two methods, as the server is unable to make

    this comparison.


    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive.

    Therefore the API specification may not document some non-mandatory error

    statuses as indicated in `CAMARA API Design Guide`.


    Please refer to the `CAMARA_common.yaml` of the Commonalities Release

    associated to this API version for a complete list of error responses.

    The applicable Commonalities Release can be identified in the

    `API Readiness Checklist` document associated to this API version.


    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible

    error response if it is explicitly documented in the API.

    # FAQ''s

    (FAQs will be added in a later version of the documentation)

    '
  version: wip
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.6
servers:
- url: '{apiRoot}/call-forwarding-signal/vwip'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
- name: Roaming status retrieval
  description: Operation to get device roaming status and country information (if roaming) synchronously
paths:
  /retrieve:
    post:
      tags:
      - Roaming status retrieval
      summary: Get the current roaming status and the country information
      description: Get the current roaming status and the country information
      operationId: getRoamingStatus
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      security:
      - openId:
        - device-roaming-status:read
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoamingStatusRequest'
        required: true
      responses:
        '200':
          description: Contains information about current roaming status
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoamingStatusResponse'
              examples:
                No-Country-Name:
                  value:
                    lastStatusTime: '2024-02-20T10:41:38.657Z'
                    roaming: true
                    countryCode: 901
                    countryName: []
                Single-Country-Code:
                  value:
                    lastStatusTime: '2024-02-20T10:41:38.657Z'
                    roaming: true
                    countryCode: 262
                    countryName:
                    - DE
                Multiple-Country-Codes:
                  value:
                    lastStatusTime: '2024-02-20T10:41:38.657Z'
                    roaming: true
                    countryCode: 340
                    countryName:
                    - BL
                    - GF
                    - GP
                    - MF
                    - MQ
        '400':
          $ref: '#/components/responses/Generic400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
        '422':
          $ref: '#/components/responses/Generic422'
        '429':
          $ref: '#/components/responses/Generic429'
        '503':
          $ref: '#/components/responses/Generic503'
components:
  schemas:
    ActiveRoaming:
      description: Roaming status. True, if it is roaming
      type: boolean
    LastStatusTime:
      description: Last time that the associated device roaming status was updated
      type: string
      format: date-time
      example: '2024-02-20T10:41:38.657Z'
    CountryCode:
      description: The Mobile country code (MCC) as an geographic region identifier for the country and the dependent areas.
      type: integer
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: 84.125.93.10
    RoamingStatusResponse:
      type: object
      required:
      - roaming
      properties:
        lastStatusTime:
          $ref: '#/components/schemas/LastStatusTime'
        roaming:
          $ref: '#/components/schemas/ActiveRoaming'
        countryCode:
          $ref: '#/components/schemas/CountryCode'
        countryName:
          $ref: '#/components/schemas/CountryName'
    PhoneNumber:
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
      type: string
      pattern: ^\+[1-9][0-9]{4,14}$
      example: '+123456789'
    DeviceIpv4Addr:
      type: object
      description: 'The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).


        If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.


        If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)


        In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.

        '
      properties:
        publicAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        privateAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        publicPort:
          $ref: '#/components/schemas/Port'
      anyOf:
      - required:
        - publicAddress
        - privateAddress
      - required:
        - publicAddress
        - publicPort
      example:
        publicAddress: 84.125.93.10
        publicPort: 59765
    ErrorInfo:
      description: The error object used for error-cases.
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
    DeviceIpv6Address:
      description: 'The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g. adding ::0 to the /64 prefix).

        '
      type: string
      format: ipv6
      example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
    RoamingStatusRequest:
      description: The request for retrieving the current roaming status for the requested device.
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
    CountryName:
      description: The ISO 3166 ALPHA-2 country-codes of mapped to mobile country code(MCC). If there is mapping of one MCC to multiple countries, then we have list of countries. If there is no mapping of MCC to any country, then an empty array [] shall be returned..
      type: array
      items:
        type: string
    Port:
      description: TCP or UDP port number
      type: integer
      minimum: 0
      maximum: 65535
    Device:
      description: 'End-user equipment able to connect to a mobile network. Examples of devices include smartphones or IoT sensors/actuators.


        The developer can choose to provide the below specified device identifiers:


        * `ipv4Address`

        * `ipv6Address`

        * `phoneNumber`

        * `networkAccessIdentifier`


        NOTE: the MNO might support only a subset of these options. The API invoker can provide multiple identifiers to be compatible across different MNOs. In this case the identifiers MUST belong to the same device.

        '
      type: object
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        networkAccessIdentifier:
          $ref: '#/components/schemas/NetworkAccessIdentifier'
        ipv4Address:
          $ref: '#/components/schemas/DeviceIpv4Addr'
        ipv6Address:
          $ref: '#/components/schemas/DeviceIpv6Address'
      minProperties: 1
    NetworkAccessIdentifier:
      description: A public identifier addressing a subscription in a mobile network. In 3GPP terminology, it corresponds to the GPSI formatted with the External Identifier ({Local Identifier}@{Domain Identifier}). Unlike the telephone number, the network access identifier is not subjected to portability ruling in force, and is individually managed by each operator.
      type: string
      example: 123456789@domain.com
  responses:
    Generic503:
      description: Service Unavailable
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 503
                code:
                  enum:
                  - UNAVAILABLE
          examples:
            GENERIC_503_UNAVAILABLE:
              description: Service is not available. Temporary situation usually related to maintenance process in the server side
              value:
                status: 503
                code: UNAVAILABLE
                message: Network issue
    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - IDENTIFIER_MISMATCH
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNSUPPORTED_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
          examples:
            GENERIC_422_IDENTIFIER_MISMATCH:
              description: Inconsistency between identifiers not pointing to the same device
              value:
                status: 422
                code: IDENTIFIER_MISMATCH
                message: Provided identifiers are not consistent.
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.
    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 429
                code:
                  enum:
                  - QUOTA_EXCEEDED
                  - TOO_MANY_REQUESTS
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: Access to the API has been temporarily blocked due to rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
                  - AUTHENTICATION_REQUIRED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials.
            GENERIC_401_AUTHENTICATION_REQUIRED:
              description: New authentication is needed, authentication is no longer valid
              value:
                status: 401
                code: AUTHENTICATION_REQUIRED
                message: New authentication is required.
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - NOT_FOUND
                  - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: The phone number is not associated with a CSP customer account
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: The phone number provided is not associated with a customer account
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{0,55}$
        example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{0,55}$
        example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
  securitySchemes:
    openId:
      description: to support Consent Management
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/CallForwardingSignal
