openapi: 3.0.3
info:
  title: Call Forwarding Signal Age Verification Send SMS API
  description: '# Overview

    The Call Forwarding Signal API provides the API Consumer with

    information about the status of the Call Forwarding Service on a specific

    phone number. The main scope of the Call Forwarding Signal API is "anti

    Fraud" to avoid fraudsters to use the Call Forwarding Service to carry

    on a scam. Other use cases are anyway supported by the Call Forwarding

    Signal API that also

    provides additional endpoints to detect the general Call Forwarding

    Service settings.

    # Introduction

    The Call Forwarding Service is provided by the Network to a phone

    number. This service redirects the incoming call to that phone number

    to an alternative destination such as another phone number or a voice mail

    system. There are two main types of call forwarding settings:

    unconditional and conditional.

    The Call Forwarding Signal API can be invoked to detect if the unconditional

    call forwarding service is active. The Call Forwarding Signal API can also

    be invoked to

    get the general status of the Call Forwarding Service (inactive,

    conditional, unconditional). If conditional call forwarding is active,

    the different type of settings are returned (''conditional_busy'',

    ''conditional_not_reachable'', ''conditional_no_answer'').


    **Example use cases:**


    [**Bank Frauds**](https://github.com/camaraproject/CallForwardingSignal/discussions/3#discussioncomment-8694420)


    [**Alert Interception**](https://github.com/camaraproject/CallForwardingSignal/discussions/3#discussioncomment-8701847)


    [**Call Forwarding Verification**](https://github.com/camaraproject/CallForwarding\Signal/discussions/3#discussioncomment-8915595)

    # Quick Start

    The Call Forwarding Signal API is a REST API based on the

    CreateCallForwardingSignal resource.

    This resource can be used, by the API Consumer, to specify the phone number

    on which the Call Forwarding Service status must be verified, in case of

    two-legged authentication. If three-legged authentication is used the phone

    number is instead detected, by the API Producer, from the access token.


    Before starting to use the Call Forwarding API, the developer needs to know

    about the below specified details:


    **phoneNumber**

    This is the end user phone number. The Call Forwarding Signal API verifies

    if a call forwarding

    service is active on this phone number. Note: this parameter must be

    must be provided/valued only in case of two-legged authentication.

    In case of three-legged authentication the phone number is retrieved by

    the access token.


    **CreateCallForwardingSignal**

    This is the resource the API Consumer uses to define the phone number to

    be verified about the status of the Network Call Forwarding service.


    **UnconditionalCallForwardingSignal**

    This is the resource the API Consumer gets back, containing the information

    about the Unconditional Call Forwarding Service status for the given phone

    number (PhoneNumber).


    **CallForwardingSignal**

    This is the resource the API Consumer gets back, containing the information

    about the general status of the Network Call Forwarding service for the

    specified phone number.


    The Call Forwarding Signal API provides two endpoints fulfilling the

    following intents:

    - **unconditional-call-forwardings**: Is the unconditional call fwd service

    active on a specific phone number?

    - **call-forwardings**: Which is the status of the call forwarding for a

    specific phone number?

    # API Documentation

    ## Details

    The Call Forwarding Signal API is invoked by an API Consumer after the

    Consent Management flow.


    The API Consumer can request the API Producer for the status of the

    Unconditional Call Forwarding service using the

    unconditional-call-forwardings POST method. A boolean, with the information

    about the activation status of the call forwarding service, will be

    provided back via the UnconditionalCallForwardingSignal resource.


    The API Consumer can also request the API Producer for the generic status of

    the Call Forwarding service using the call-forwardings POST method. An array

    of strings with the information of the type of active call forwarding

    services will be provided back via the CallForwardingSignal resource.

    # Authorization and authentication

    The "Camara Security and Interoperability Profile" provides details of how

    an API consumer requests an access token. Please refer to Identity and

    Consent Management

    (https://github.com/camaraproject/IdentityAndConsentManagement/)

    for the released version of the profile.


    The specific authorization flows to be used will be agreed upon during the

    onboarding process, happening between the API consumer and the API

    provider, taking into account the declared purpose for accessing the API,

    whilst also being subject to the prevailing legal framework dictated by

    local legislation.


    In cases where personal data is processed by the API and users can

    exercise their rights through mechanisms such as opt-in and/or opt-out,

    the use of three-legged access tokens is mandatory. This ensures that

    the API remains in compliance with privacy regulations, upholding the

    principles of transparency and user-centric privacy-by-design.

    # Identifying the phone number from the access token

    This API requires the API consumer to identify a phone number as the

    subject of the API as follows:

    - When the API is invoked using a two-legged access token, the subject

    will be identified from the optional `phoneNumber` object field, which

    therefore MUST be provided.

    - When a three-legged access token is used however, this optional

    identifier MUST NOT be provided, as the subject will be uniquely

    identified from the access token.


    This approach simplifies API usage for API consumers using a

    three-legged access token to invoke the API by relying on the

    information that is associated with the access token and was

    identified during the authentication process.

    ## Error handling:


    - If the subject cannot be identified from the access token and the

    optional `phoneNumber` object field is not included in the request, then

    the server will return an error with the

    `422 MISSING_IDENTIFIER` error code.


    - If the subject can be identified from the access token and the

    optional `phoneNumber` object field is also included in the request, then

    the server will return an error with the `422 UNNECESSARY_IDENTIFIER`

    error code. This will be the case even if the same device is

    identified by these two methods, as the server is unable to make

    this comparison.


    # Additional CAMARA error responses

    The list of error codes in this API specification is not exhaustive.

    Therefore the API specification may not document some non-mandatory error

    statuses as indicated in `CAMARA API Design Guide`.


    Please refer to the `CAMARA_common.yaml` of the Commonalities Release

    associated to this API version for a complete list of error responses.

    The applicable Commonalities Release can be identified in the

    `API Readiness Checklist` document associated to this API version.


    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible

    error response if it is explicitly documented in the API.

    # FAQ''s

    (FAQs will be added in a later version of the documentation)

    '
  version: wip
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.6
servers:
- url: '{apiRoot}/call-forwarding-signal/vwip'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
- name: Send SMS
paths:
  /short-message:
    post:
      security:
      - openId:
        - send-sms:short-message
      tags:
      - Send SMS
      summary: Send SMS
      description: 'The customer application server makes a request to the SMS API to send SMS message to the destination address.

        '
      operationId: send-sms
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: 'Submit a request for sending SMS to the destination address

          '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              MessageRequest:
                value:
                  to:
                  - '+910123456789'
                  from: '+919876543210'
                  category: PROMOTION
                  message: xxxxxxxxxx
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Generic200'
        '400':
          $ref: '#/components/responses/Generic400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
        '500':
          $ref: '#/components/responses/Generic500'
        '503':
          $ref: '#/components/responses/Generic503'
components:
  responses:
    Generic503:
      description: Service unavailable. Typically the server is down.
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            status: 503
            code: UNAVAILABLE
            detail: Service unavailable
    Generic200:
      description: OK
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageResponse'
          example:
            msgId: 56647d96-b3e6-48d2-b93f-ab0d56bdd965
            timestamp: '2024-03-19T12:33:27.070Z'
    Generic401:
      description: Authentication problem with the client request
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            status: 401
            code: UNAUTHENTICATED
            detail: Request not authenticated due to missing, invalid, or expired credentials
    Generic403:
      description: Client does not have sufficient permission
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            PermissionDenied:
              value:
                status: 403
                code: PERMISSION_DENIED
                detail: Client does not have sufficient permissions to perform this action
            InvalidTokenContext:
              value:
                status: 403
                code: INVALID_TOKEN_CONTEXT
                detail: Phone number cannot be deducted from access token context
    Generic400:
      description: Problem with the client request
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            status: 400
            code: INVALID_ARGUMENT
            detail: Client specified an invalid argument, request body or query param
    Generic500:
      description: Server error
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            status: 500
            code: INTERNAL
            detail: Server error
    Generic404:
      description: Resource Not Found
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            status: 404
            code: NOT_FOUND
            detail: A specified resource is not found
  schemas:
    MessageResponse:
      type: object
      required:
      - msgId
      - timestamp
      properties:
        msgId:
          type: string
          description: The SMS messages sent to the recipients are identified by smsnumber are identified.
        timestamp:
          type: string
          format: date-time
          description: Timestamp when SMS was delivered. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone. Recommended format is yyyy-MM-dd'T'HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z)
    MessageRequest:
      type: object
      required:
      - to
      - from
      - message
      properties:
        to:
          type: array
          description: The recipients MSISDN
          items:
            type: string
        from:
          type: string
          description: The senders MSISDN
        category:
          type: string
          enum:
          - PROMOTION
          - SERVICE
          - TRANSACTION
        message:
          type: string
          description: SMS message
    ErrorInfo:
      type: object
      required:
      - status
      - code
      - detail
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Code given to this error
        detail:
          type: string
          description: Detailed error description
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
  securitySchemes:
    openId:
      description: to support Consent Management
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/CallForwardingSignal
