openapi: 3.2.0
info:
  title: Know Your Customer Fill In API
  description: This API provides the customer with the ability request and receive the information for a particular user, which on file (and verified) by the user's Operator in their own KYC records, in order for the SP to confirm the accuracy of the information and provide a specific service to the user.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.3.0
  x-camara-commonalities: 0.5
servers:
- url: '{apiRoot}/kyc-fill-in/v0.3'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
- name: Fill-in
  description: Operations to provide information related to a customer identity stored the account data bound to the customer's phone number.
paths:
  /fill-in:
    post:
      tags:
      - Fill-in
      summary: Providing information related to a customer identity stored the account data…
      operationId: KYC_Fill-in
      security:
      - openId:
        - kyc-fill-in:set-all
      - openId:
        - kyc-fill-in:phoneNumber
      - openId:
        - kyc-fill-in:idDocument
      - openId:
        - kyc-fill-in:name
      - openId:
        - kyc-fill-in:givenName
      - openId:
        - kyc-fill-in:familyName
      - openId:
        - kyc-fill-in:nameKanaHankaku
      - openId:
        - kyc-fill-in:nameKanaZenkaku
      - openId:
        - kyc-fill-in:middleNames
      - openId:
        - kyc-fill-in:familyNameAtBirth
      - openId:
        - kyc-fill-in:address
      - openId:
        - kyc-fill-in:streetName
      - openId:
        - kyc-fill-in:streetNumber
      - openId:
        - kyc-fill-in:postalCode
      - openId:
        - kyc-fill-in:region
      - openId:
        - kyc-fill-in:locality
      - openId:
        - kyc-fill-in:country
      - openId:
        - kyc-fill-in:houseNumberExtension
      - openId:
        - kyc-fill-in:birthdate
      - openId:
        - kyc-fill-in:email
      - openId:
        - kyc-fill-in:gender
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KYC_FillinRequest'
            examples:
              KYC_FillInBodyExample:
                value:
                  phoneNumber: '+34629255833'
      responses:
        '200':
          description: OK
          headers:
            x-correlator:
              $ref: '#/components/headers/X-Correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KYC_FillinResponse'
              examples:
                KYC_Fillin200Example:
                  value:
                    phoneNumber: '+34629255833'
                    idDocument: 66666666q
                    name: Federica Sanchez Arjona
                    givenName: Federica
                    familyName: Sanchez Arjona
                    nameKanaHankaku: federica
                    nameKanaZenkaku: Ｆｅｄｅｒｉｃａ
                    middleNames: Sanchez
                    familyNameAtBirth: YYYY
                    address: Tokyo-to Chiyoda-ku Iidabashi 3-10-10
                    streetName: Nicolas Salmeron
                    streetNumber: 4
                    postalCode: 1028460
                    region: Tokyo
                    locality: ZZZZ
                    country: JP
                    houseNumberExtension: 36
                    birthdate: '1978-08-22'
                    email: abc@example.com
                    gender: male
        '400':
          $ref: '#/components/responses/Generic400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
        '422':
          $ref: '#/components/responses/Generic422'
components:
  responses:
    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: The phone number is not associated with a CSP customer account
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: The phone number provided is not associated with a customer account
    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service is not applicable for the provided phone number
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not applicable for the provided phone number
            GENERIC_422_MISSING_IDENTIFIER:
              description: No phone number has been provided either explicitly or associated with the access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: No phone number has been provided
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit phone number has been provided when one is already associated with the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: An explicit phone number has been provided when one is already associated with the access token
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
                  - AUTHENTICATION_REQUIRED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials.
            GENERIC_401_AUTHENTICATION_REQUIRED:
              description: New authentication is needed, authentication is no longer valid
              value:
                status: 401
                code: AUTHENTICATION_REQUIRED
                message: New authentication is required.
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
  headers:
    X-Correlator:
      description: Correlation id for the different services
      required: false
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{1,55}$
        example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
  schemas:
    KYC_FillinResponse:
      type: object
      properties:
        phoneNumber:
          type: string
          description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
          pattern: ^\+[1-9][0-9]{4,14}$
          example: '+123456789'
        idDocument:
          type: string
          description: Id number associated to the id_document of the customer stored on the Operator's system.
        name:
          type: string
          description: Complete name of the customer stored on the Operator's system.  It is usually composed of first/given name and last/family/sur- name in a country.  Depending on the country, the order of first/give name and last/family/sur- name varies, and middle name could be included.  It can use givenName, middleNames, familyName and/or familyNameAtBirth. For example, in ESP, name+familyName; in NLD, it can be name+middleNames+familyName or name+middleNames+familyNameAtBirth, etc.
        givenName:
          type: string
          description: First/given name or compound first/given name of the customer on the Operator's system.
        familyName:
          type: string
          description: Last name, family name, or surname of the customer stored on the Operator's system.
        nameKanaHankaku:
          type: string
          description: Complete name of the customer in Hankaku-Kana format (reading of name) for Japan, stored on the Operator's system.
        nameKanaZenkaku:
          type: string
          description: Complete name of the customer in Zenkaku-Kana format (reading of name) for Japan, stored on the Operator's system.
        middleNames:
          type: string
          description: Middle name/s of the customer stored on the Operator's system.
        familyNameAtBirth:
          type: string
          description: Last/family/sur- name at birth of the customer stored on the Operator's system.
        address:
          type: string
          description: Complete address of the customer stored on the Operator's system.  For some countries, it is built following the usual concatenation of parameters in a country, but for other countries, this is not the case.  For some countries, it can use streetName, streetNumber and/or houseNumberExtension. For example, in ESP, streetName+streetNumber; in NLD, it can be streetName+streetNumber or streetName+streetNumber+houseNumberExtension.
        streetName:
          type: string
          description: Name of the street of the customer's address on the Operator's system.  It should not include the type of the street.
        streetNumber:
          type: string
          description: The street number of the customer's address on the Operator's system.  Number identifying a specific property on the 'streetName'.
        postalCode:
          type: string
          description: The postal code or Zip code of the customer's address, stored on the Operator's system.
        region:
          type: string
          description: Region/prefecture of the customer's address, stored on the Operator's system.
        locality:
          type: string
          description: Locality of the customer's address, stored on the Operator's system.
        country:
          type: string
          description: Country of the customer's address stored on the Operator's system. Format ISO 3166-1 alpha-2.
        houseNumberExtension:
          type: string
          description: House number extension of the customer stored on the Operator's system.  Specific identifier of the house needed depending on the property type. For example, number of apartment in an apartment building.
        birthdate:
          type: string
          format: date
          description: Birthdate of the customer, in ISO 8601 calendar date format (YYYY-MM-DD), stored on the Operator's system.
        email:
          type: string
          format: email
          description: Email address of the customer in the RFC specified format (local-part@domain), stored on the Operator's system.
        gender:
          type: string
          description: Gender of the customer stored on the Operator's system (male/female/other).
          enum:
          - MALE
          - FEMALE
          - OTHER
    ErrorInfo:
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
    KYC_FillinRequest:
      type: object
      properties:
        phoneNumber:
          type: string
          description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
          pattern: ^\+[1-9][0-9]{4,14}$
          example: '+123456789'
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]{1,55}$
        example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
